# Generated by Django 2.2.8 on 2021-08-16 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('message', models.TextField(default='')),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
    ]
